/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea3;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import tarea3.Main;

/**
 *
 * @author Mark
 */
public class Cifrador_Morse extends javax.swing.JFrame {

    /**
     * Creates new form Cifrador_Morse
     */
    public Cifrador_Morse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Buscar !");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ruta del Archivo a Encriptar:");

        jButton2.setText("Cifrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Ruta del Archivo a Desifrar:");

        jButton3.setText("Buscar!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Desifrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton5.setText("Atras");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(349, 349, 349)
                            .addComponent(jButton2))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser choose = new JFileChooser();
        int option = choose.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            String file = choose.getSelectedFile().getPath();
            jTextField1.setText(file);

        } else {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser choose = new JFileChooser();
        int option = choose.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            String file = choose.getSelectedFile().getPath();
            jTextField2.setText(file);

        } else {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
        String linea, dato = "";
        String parrafo[], parrafoEncriptrado[];
        int fila;
        jTextArea1.setText("");
        jTextArea2.setText("");
        if (jTextField1.getText() == null || jTextField1.getText().isEmpty()) {
            jLabel2.setText("Escribe una ruta Correcta");
        } else {
            try {
                // Apertura del fichero y creacion de BufferedReader para poder
                // hacer una lectura comoda (disponer del metodo readLine()).
                String ruta = jTextField1.getText().toString();
                archivo = new File(ruta);

                fr = new FileReader(archivo);
                br = new BufferedReader(fr);
                fila = 0;
                while ((linea = br.readLine()) != null) {
                    System.out.println(linea);
                    fila++;
                }
                parrafo = new String[fila];
                parrafoEncriptrado = new String[fila];
                fr = new FileReader(archivo);
                br = new BufferedReader(fr);
                fila = 0;
                while ((linea = br.readLine()) != null) {
                    parrafo[fila] = linea;
                    fila++;
                }
                linea = "";
                for (int i = 0; i < fila; i++) {
                    jTextArea1.append(parrafo[i] + "\n");

                }

                /**
                 * Iniciamos La Encriptacion
                 */
                for (int i = 0; i < fila; i++) {
                    String cad = parrafo[i].toLowerCase();
                    StringTokenizer tokens = new StringTokenizer(cad);
                    while (tokens.hasMoreTokens()) {
                        System.out.println("tk:" + tokens.nextToken());
                    }
                    System.out.println("\n\n");
                    String palabra = cad;
                    int j = 0;
                    linea = "";

                    for (int k = 0; k < palabra.length(); k++) {

                        System.out.println("Entro whiile " + palabra.charAt(k));
                        if (palabra.charAt(k) == ('a')) {
                            System.out.print(".-");
                            dato = ".-";
                        } else if (palabra.charAt(k) == ('b')) {
                            System.out.print("-...");
                            dato = "-...";
                        } else if (palabra.charAt(k) == ('c')) {
                            System.out.print("-.-.");
                            dato = "-.-.";
                        } else if (palabra.charAt(k) == ('d')) {
                            System.out.print("-..");
                            dato = "-..";
                        } else if (palabra.charAt(k) == ('e')) {
                            System.out.print(".");
                            dato = (".");
                        } else if (palabra.charAt(k) == ('f')) {
                            System.out.print("..-.");
                            dato = ("..-.");
                        } else if (palabra.charAt(k) == ('g')) {
                            System.out.print("--.");
                            dato = ("--.");
                        } else if (palabra.charAt(k) == ('h')) {
                            System.out.print("...");
                            dato = ("...");
                        } else if (palabra.charAt(k) == ('i')) {
                            System.out.print("..");
                            dato = ("..");
                        } else if (palabra.charAt(k) == ('j')) {
                            System.out.print(".---");
                            dato = (".---");
                        } else if (palabra.charAt(k) == ('k')) {
                            System.out.print("-.-");
                            dato = ("-.-");
                        } else if (palabra.charAt(k) == ('l')) {
                            System.out.print(".-..");
                            dato = (".-..");
                        } else if (palabra.charAt(k) == ('m')) {
                            System.out.print("--");
                            dato = ("--");
                        } else if (palabra.charAt(k) == ('n')) {
                            System.out.print("-.");
                            dato = ("-.");
                        } else if (palabra.charAt(k) == ('o')) {
                            System.out.print("---");
                            dato = ("---");
                        } else if (palabra.charAt(k) == ('p')) {
                            System.out.print(".--.");
                            dato = (".--.");
                        } else if (palabra.charAt(k) == ('q')) {
                            System.out.print("--.-");
                            dato = ("--.-");
                        } else if (palabra.charAt(k) == ('r')) {
                            System.out.print(".-.");
                            dato = (".-.");
                        } else if (palabra.charAt(k) == ('s')) {
                            System.out.print("...");
                            dato = ("...");
                        } else if (palabra.charAt(k) == ('t')) {
                            System.out.print("-");
                            dato = ("-");
                        } else if (palabra.charAt(k) == ('u')) {
                            System.out.print("..-");
                            dato = ("..-");
                        } else if (palabra.charAt(k) == ('v')) {
                            System.out.print("...-");
                            dato = ("...-");
                        } else if (palabra.charAt(k) == ('w')) {
                            System.out.print(".--");
                            dato = (".--");
                        } else if (palabra.charAt(k) == ('x')) {
                            System.out.print("-..-");
                            dato = ("-..-");
                        } else if (palabra.charAt(k) == ('y')) {
                            System.out.print("-.--");
                            dato = ("-.--");
                        } else if (palabra.charAt(k) == ('z')) {
                            System.out.print("--..");
                            dato = ("--..");
                        } else if (palabra.charAt(k) == (' ')) {
                            System.out.print("/");
                            dato = ("/");
                        }

                        linea = linea + dato + " ";

                    }
                    jTextArea2.append(linea + "\n");
                    parrafoEncriptrado[i] = linea;
                    j++;
                    System.out.print(linea);
                }

                jLabel2.setText("Texto Encriptado!!");

                archivo = new File(ruta);
                BufferedWriter bw;
                try {
                    bw = new BufferedWriter(new FileWriter(archivo));
                    for (int i = 0; i < fila; i++) {
                        bw.write(parrafoEncriptrado[i] + "\n");
                    }
                    bw.close();
                } catch (Exception e) {
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                // En el finally cerramos el fichero, para asegurarnos
                // que se cierra tanto si todo va bien como si salta 
                // una excepcion.
                try {
                    if (null != fr) {
                        fr.close();
                    }
                } catch (Exception e2) {
                    e2.printStackTrace();
                }
            }

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
        String linea, dato = "";
        String parrafo[], parrafoEncriptrado[];
        int fila;
        jTextArea1.setText("");
        jTextArea2.setText("");
        if (jTextField2.getText() == null || jTextField2.getText().isEmpty()) {
            jLabel2.setText("Escribe una ruta Correcta");
        } else {
            try {
                // Apertura del fichero y creacion de BufferedReader para poder
                // hacer una lectura comoda (disponer del metodo readLine()).
                String ruta = jTextField2.getText().toString();
                archivo = new File(ruta);

                fr = new FileReader(archivo);
                br = new BufferedReader(fr);
                fila = 0;
                while ((linea = br.readLine()) != null) {
                    System.out.println(linea);
                    fila++;
                }
                parrafo = new String[fila];
                parrafoEncriptrado = new String[fila];
                fr = new FileReader(archivo);
                br = new BufferedReader(fr);
                fila = 0;
                while ((linea = br.readLine()) != null) {
                    parrafo[fila] = linea;
                    fila++;
                }
                linea = "";
                for (int i = 0; i < fila; i++) {
                    jTextArea1.append(parrafo[i] + "\n");

                }

                /**
                 * Iniciamos La Encriptacion
                 */
                for (int i = 0; i < fila; i++) {
                    String cad = parrafo[i];
                    StringTokenizer tokens = new StringTokenizer(cad);
                    while (tokens.hasMoreTokens()) {
                        System.out.println("tk:" + tokens.nextToken());
                    }
                    System.out.println("\n\n");
                    String[] palabra = cad.split("\\ ");
                    int j = 0;
                    linea = "";

                    while (j <= palabra.length - 1) {

                        if (palabra[j].equals(".-")) {
                            System.out.print("A");

                            dato = ("A");
                        } else if (palabra[j].equals("-...")) {
                            System.out.print("B");
                            dato = ("B");
                        } else if (palabra[j].equals("-.-.")) {
                            System.out.print("C");

                            dato = ("C");
                        } else if (palabra[j].equals("-..")) {
                            System.out.print("D");

                            dato = ("D");
                        } else if (palabra[j].equals(".")) {
                            System.out.print("E");

                            dato = ("E");
                        } else if (palabra[j].equals("..-.")) {
                            System.out.print("F");

                            dato = ("F");
                        } else if (palabra[j].equals("--.")) {
                            System.out.print("G");

                            dato = ("G");
                        } else if (palabra[j].equals("...")) {
                            System.out.print("H");

                            dato = ("H");
                        } else if (palabra[j].equals("..")) {
                            System.out.print("I");

                            dato = ("I");
                        } else if (palabra[j].equals(".---")) {
                            System.out.print("J");

                            dato = ("J");
                        } else if (palabra[j].equals("-.-")) {
                            System.out.print("K");

                            dato = ("K");
                        } else if (palabra[j].equals(".-..")) {
                            System.out.print("L");

                            dato = ("L");
                        } else if (palabra[j].equals("--")) {
                            System.out.print("M");

                            dato = ("M");
                        } else if (palabra[j].equals("-.")) {
                            System.out.print("N");

                            dato = ("N");
                        } else if (palabra[j].equals("---")) {
                            System.out.print("O");

                            dato = ("O");
                        } else if (palabra[j].equals(".--.")) {
                            System.out.print("P");

                            dato = ("P");
                        } else if (palabra[j].equals("--.-")) {
                            System.out.print("Q");

                            dato = ("Q");
                        } else if (palabra[j].equals(".-.")) {
                            System.out.print("R");

                            dato = ("R");
                        } else if (palabra[j].equals("...")) {
                            System.out.print("S");

                            dato = ("S");
                        } else if (palabra[j].equals("-")) {
                            System.out.print("T");

                            dato = ("T");
                        } else if (palabra[j].equals("..-")) {
                            System.out.print("U");

                            dato = ("U");
                        } else if (palabra[j].equals("...-")) {
                            System.out.print("V");

                            dato = ("V");
                        } else if (palabra[j].equals(".--")) {
                            System.out.print("W");

                            dato = ("W");
                        } else if (palabra[j].equals("-..-")) {
                            System.out.print("X");

                            dato = ("X");
                        } else if (palabra[j].equals("-.--")) {
                            System.out.print("Y");

                            dato = ("Y");
                        } else if (palabra[j].equals("--..")) {
                            System.out.print("Z");
                            dato = ("Z");
                        }else if (palabra[j].equals("/")) {
                            System.out.print(" ");
                            dato = (" ");
                        }

                        linea = linea + dato + "";
                        j++;
                    }

                    jTextArea2.append(linea + "\n");
                    parrafoEncriptrado[i] = linea;
                    System.out.print(linea);
                }

                jLabel2.setText("Texto Encriptado!!");

                archivo = new File(ruta);
                BufferedWriter bw;
                try {
                    bw = new BufferedWriter(new FileWriter(archivo));
                    for (int i = 0; i < fila; i++) {
                        bw.write(parrafoEncriptrado[i] + "\n");
                    }
                    bw.close();
                } catch (Exception e) {
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                // En el finally cerramos el fichero, para asegurarnos
                // que se cierra tanto si todo va bien como si salta 
                // una excepcion.
                try {
                    if (null != fr) {
                        fr.close();
                    }
                } catch (Exception e2) {
                    e2.printStackTrace();
                }
            }

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:        
        Main panel = new Main();
                panel.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cifrador_Morse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cifrador_Morse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cifrador_Morse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cifrador_Morse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cifrador_Morse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
